name: build and test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: build and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build tests
      run: ./build/generate_tests.sh
    - name: run conversion test
      run: ./build/test_conversions
    - name: run main test
      run: ./build/test_main

