name: build and test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: build and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create build directory
      run: mkdir -p build
    - name: move to build directory
      run: cd build
    - name: configure
      run: cmake .. -DPHQ_TEST=ON
    - name: build
      run: make -j
    - name: test
      run: make test

